data:
  train: /home/majeed/data/gender/train
  test: /home/majeed/data/gender/test
project:
  path: output
pipeline:
  - name: 'mobilenet_v2'
    input_layer:
      image_height: 224
      image_width: 224
      color_channels: 3
    pretrained_model:
      include_top: false
      weights: 'imagenet'
    output_layer:  # output layer is a classifier / regressor
      units: 2
      activation: "softmax"